# Markov Chain Monte Carlo

Let's get our import statements out of the way
Numpy will let us pull random numbers and manage our lists more easily
matplotlib will be used for plotting our results

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Just the Monte Carlo

Monte Carlo is a process of **approximating a distribution** by *simulating an event* many times and recording the outcomes.

The simplest example would be rolling a d6 over and over again, and recording the result each time. At first, the counts of each number will vary, but as the number of rolls increases, the counts will converge to their theoretical value of $\frac{1}{6}$

Let's use this technique to approximate the value of $\pi$
<div>
<img src="https://learntofish.files.wordpress.com/2010/10/circle_and_square.png" width="300"/>
</div>

Consider the areas of the shapes above.

Area of circle = $\pi r^{2}$

Area of square = $(2r)^{2}$

### R = $\frac{\text{Area of circle}}{\text{Area of square}} = \frac{\pi r^{2}}{4 r^{2}} = \frac{\pi}{4}$

### $ 4R = \pi $

Now we just need to calculate R.

We'll do this by _randomly_ dropping points into the square. If a point is also inside the circle, we'll record it and mark it in a different color.

Fill in the gaps in the code below, and then use the subsequent cells to test your code

In [ ]:
def approximate_pi(num_sample):
    in_square = [[], []]
    in_circle = [[], []]
    
    for i in range(num_sample):
        # Generate uniform random values within the bounds of a square centered at the origin and with side length 2
        # Use numpy.random.uniform to generate these values 
        x = np.random.uniform(# YOUR CODE HERE)
        y = np.random.uniform(# YOUR CODE HERE)
    
        in_square[0].append(x)
        in_square[1].append(y)

        # Check if the point is also inside the circle
        if(# YOUR CODE HERE):
            in_circle[0].append(x)
            in_circle[1].append(y)

    # Plot the results
    fig = plt.figure(figsize=(8,8))
    ax = fig.gca()
    circ = plt.Circle((0, 0), 1, color='black', fill=False)
    # Draw our circle and square for clarity
    ax.add_patch(circ)
    square_x = [-1, 1, 1, -1, -1]
    square_y = [-1, -1, 1, 1, -1]
    plt.plot(square_x, square_y, color = "black")
    plt.xlim((-1.5,1.5))
    plt.ylim((-1.5,1.5))
    plt.scatter(in_square[0], in_square[1], color="r", s=5)
    plt.scatter(in_circle[0], in_circle[1], color="b", s=5)
    plt.show()
    # Calculate R and pi
    print("R = " + str(len(in_circle[0])/len(in_square[0])))
    print("pi = " + str(4*len(in_circle[0])/len(in_square[0])))

In [ ]:
approximate_pi(1000)

In [ ]:
approximate_pi(10000)

## Just the Markov Chain

A Markov chain is a mathematical structure that defines state transitions in a stochastic (probabilistic) way.

If you're familiar with Finite State Machines or Turing Machines, this is similar to those.
But Markov Chains have a key difference in that they do not have inputs. State transitions are purely stochastic.

Like some FSMs, however, Markov Chains are *memoryless*.
The next state is dependent ONLY on the current state

Let's work through an example using the weather:

<div>
<img src="https://deparkes.co.uk/wp-content/uploads/2020/08/GraphView.png" width="500"/>
</div>

This is a gross oversimplification of how the weather works, because weather patterns are not memoryless, and there are far more options than these three states.

BUT. It will work for us!

Here, we will use the following values to represent each of our states

| State  | Weather  |
|---|---|
| 1 | Sunny |
| 2 | Cloudy  |
| 3 | Rainy  |

The graph above tells us that, if today is sunny, there is a 70% chance that tomorrow will also be sunny, a 10% chance tomorrow will be cloudy, and a 20% chance tomorrow will be rainy.

If today is cloudy, there is a 30% chance tomorrow will also be cloudy, a 50% chance tomorrow will be rainy, and a 20% chance tomorrow will be sunny.

If today is rainy, there is a 60% chance tomorrow will also be rainy, a 10% chance tomorrow will be sunny, and a 30% chance tomorrow will be cloudy.

We will represent our Markov chain as an array (a list in python), as follows:

| Day  | Day 1  | Day 2  | ...  | Day N  |
|---|---|---|---|---|
|State| 1 | 3 |...|2|

We'll start by creating an empty list, then picking the state for the first day.

For each day after that, we'll generate a random number, and then use the probabilities listed above to decide what the next day's weather (state) will be.

Fill in the following code to achieve this:

In [ ]:
def approximate_weather_distribution(num_steps):
    # Create our empty list of a given number of steps (days)
    weather_chain = np.zeros(num_steps)

    # Set the state of the first day; Integer value for the state
    weather_chain[0] = # -- YOUR CODE HERE --
    
    for i in range(len(weather_chain)-1):
        # Check if today is sunny
        if(weather_chain[i] == 1):
            random_value = np.random.uniform(0,10)
            # Check if we transition to state 2 (cloudy)
            if(# -- YOUR CODE HERE --):
                weather_chain[i+1] = 2
            # Check if we transition to state 3 (rainy)
            elif(# -- YOUR CODE HERE --):
                weather_chain[i+1] = 3
            else:
                weather_chain[i+1] = 1
        # Check if today is cloudy
        elif(weather_chain[i] == 2):

            # -- YOUR CODE HERE --

        # Check if today is rainy
        elif(weather_chain[i] == 3):

            # -- YOUR CODE HERE --

    # Plot our steps
    plt.figure(figsize=(4,4))
    plt.plot(weather_chain)
    plt.show()
    # Plot our Distribution
    plt.figure(figsize=(4,4))
    plt.hist(weather_chain)
    plt.show()
    # Print our results for the distribution
    num_sunny = len(weather_chain[np.where(weather_chain == 1)])
    num_cloudy = len(weather_chain[np.where(weather_chain == 2)])
    num_rainy = len(weather_chain[np.where(weather_chain == 3)])
    print("Sunny: " + str(num_sunny/len(weather_chain)))
    print("Cloudy: " + str(num_cloudy/len(weather_chain)))
    print("Rainy: " + str(num_rainy/len(weather_chain)))

In [ ]:
approximate_weather_distribution(1000)

In [ ]:
approximate_weather_distribution(100000)

## Markov Chain Monte Carlo 

Markov Chain Monte Carlo combines the above techniques to sample from an unknown probability distribution.

As above, the more chains we have (number of monte carlo events) and the longer the chains are (more steps in each chain) the better our approximation is!

Markov Chain Monte Carlo (MCMC) is rooted in Baye's Theorem
<div>
<img src="https://miro.medium.com/v2/resize:fit:1400/0*x96Ttm0fzmY6eQxH.jpg" width="500"/>
</div>

We won't spend much time on Bayes theorem today, but if you're interested in discrete math and probability, or you think you might want to get into machine learning and artificial intelligence, Bayesian statistics will prove super useful to you!

P(B) above is also sometimes called the evidence, and for our purposes, we will normalize it to 1 (which is a fancy way of saying, it's a scaling constant so we'll ignore it for now)

Today, we're going to consider a relevant example of approximating the hubble constant and a scaling relationship with redshift (~ distance)

I've already prepared the data for you to load. It's in a 4 column CSV that takes the form of

| z  | z_error  | H0  | H0_error  | 
|---|---|---|---|
| |  |  ||
| |  |  ||
| |  |  ||



#### Step 1. Load Our Data

I've provide this for you below. The table can be found in the same github repo that this ipynotebook came from

In [41]:
SNe = np.loadtxt("SNe_table.csv", delimiter=",")
print(SNe)

[[1.2200000e-03 8.4000000e-04 7.3612823e+01 4.9067000e-01]
 [1.2200000e-03 8.4000000e-04 7.3400167e+01 7.8457400e-01]
 [2.5600000e-03 8.4000000e-04 7.3597874e+01 2.7680800e-01]
 ...
 [1.8011900e+00 2.0140000e-02 7.4024664e+01 1.0525100e-01]
 [1.9116500e+00 2.6300000e-03 7.3123995e+01 1.0517300e-01]
 [2.2613700e+00 2.0180000e-02 7.2739270e+01 1.0535800e-01]]


Looks good!

BUT. We probably want to be able to iterate over each column, so let's transpose our data:

In [43]:
SNe_data = SNe.transpose()
print(SNe_data)

[[1.2200000e-03 1.2200000e-03 2.5600000e-03 ... 1.8011900e+00
  1.9116500e+00 2.2613700e+00]
 [8.4000000e-04 8.4000000e-04 8.4000000e-04 ... 2.0140000e-02
  2.6300000e-03 2.0180000e-02]
 [7.3612823e+01 7.3400167e+01 7.3597874e+01 ... 7.4024664e+01
  7.3123995e+01 7.2739270e+01]
 [4.9067000e-01 7.8457400e-01 2.7680800e-01 ... 1.0525100e-01
  1.0517300e-01 1.0535800e-01]]


This gives us our original 4 columns as 4 rows.

Row 1 - redshift, Z

Row 2 - redshift error, Z_err

Row 3 - Hubble Value, H0

Row 4 - Hubble Value error, H0_err

In [74]:
my_z = SNe_data[0]
my_z_err = SNe_data[1]
my_H0 = SNe_data[2]
my_H0_err = SNe_data[3]

#### Step 2 - Define Our Model

For our purposes, we're going to simplify our model to take only 2 parameters:

### $\widetilde{H_{0}}$
### $\alpha$

and our model will take the form:

### $ H_{0}(z) = \frac{\widetilde{H_{0}}}{(1+z)^{\alpha}}$

We need a function that will evaluate $ H_{0}(z) $ at a given $\widetilde{H_{0}}$, $\alpha$, and $z$.

Please define it below:

In [49]:
def eval_model(H_0_squiggle, alpha, z):
    # return H0(z) as defined above
    return # -- YOUR CODE HERE --

#### Step 3 - Define Our Prior

Priors are sort of like an assumption or a limit. They're something that we think we know but haven't necessarily evaluated analytically.

There are many priors that are commonly used in statistics, but we will leave them alone for now.

Below, we will define our prior as a set of boundaries.

Specifically, we will set lower and upper limits on $\widetilde{H_{0}}$ and $ \alpha$

You've learned in reading and lecture some values for $ H_{0} $, so let's restrict $\widetilde{H_{0}}$ to values somewhat close to those

Let's also restrict $ \alpha$ to be a *positive* value. If you'd like, you can add an upper bound as well

In [136]:
def in_prior(H_0_squiggle, alpha):
    # Set bounds for our parameters
    if ((H_0_squiggle > "YOUR VALUE HERE") and (H_0_squiggle < "YOUR VALUE HERE") and (alpha >= "YOUR VALUE HERE") and (alpha < "YOUR VALUE HERE")):
        return True
    else:
        return False

#### Step 4 - Define Our "Likelihood" (actually least-squares)

A likelihood is a measure of how likely we see our data, assuming our model is correct.

For simplicity and familiarity, we're going to implement a $\chi^{2}$ least square test instead.

This least squarest test technically works in reverse of likelihood. The higher the value of the squares, the less likely our data is.

So where we would normally try to maximize likelihood, we're going to try to minimize least squares.

We'll define

### Least Squares = $ \sum{(\frac{y_{model} - y_{data}}{y_{error}})^{2}} $

Which will give more weight to our data points with smaller error

Please implement the least squares formula below:

In [107]:
def get_least_squares(H_0_squiggle, alpha, z, H, H_err):
    least_squares = 0
    for i in range(len(z)):
        least_squares += # -- YOUR CODE HERE --

    return least_squares

#### Step 5 - Define Our Next Step

Like with the weather example above, we need to define a process of getting our next step in our Markov chain

Here, our steps are not discrete.

We're going to start from our current location and take a step in any direction in parameter space (we're going to change $\widetilde{H_{0}}$ and $ \alpha$ by small amounts)

An easy way to do this is to take a random number from a normal or *gaussian* distribution, centered at our current point.

We'll then check if our next point is valid according to our priors. If it's not valid, we'll generate a new one until we get one that is valid.

Once we have a valid step, we'll return our new $\widetilde{H_{0}}$ and $ \alpha$

I've provided the random step for you below:

In [134]:
def get_next_step(H_0_squiggle, alpha):
    new_H_0_squiggle = np.random.normal(H_0_squiggle, .5)
    new_alpha = np.random.normal(alpha, .01)
    while(not in_prior(new_H_0_squiggle, new_alpha)):
        new_H_0_squiggle = np.random.normal(H_0_squiggle, .1)
        new_alpha = np.random.normal(alpha, .01)
    return new_H_0_squiggle, new_alpha

#### Step 6 - Place our "Walkers"

Much like how we set the state of the first day of weather, we need to define an array for our walkers and then set our initial values.

We'll keep our walkers in a table. The row will be each markov chain, and each row will be a different walker

|   | Step 0  | Step 1  | Step 2  | ...  |Step N  |
|---|---|---|---|---|---|
|Walker 1|  |  ||
|Walker 2|  |  ||
|Walker ...|  |  ||
|Walker n|  |  ||

We'll keep a separate table for each of $\widetilde{H_{0}}$ and $ \alpha$, but remember that the same row in each of the tables represents the same chain (each state is comprised by BOTH $\widetilde{H_{0}}$ and $ \alpha$)

You can set your initial values however you choose. You can place them with a uniform random number, a normal random number, or you can place them manually

Implement your initialization below:

In [ ]:
def initialize_walkers(num_walkers, num_steps):
    # Create our walker tables
    H0squiggle_walk_states = np.zeros((num_walkers, num_steps))
    alpha_walk_states = np.zeros((num_walkers, num_steps))

    # Give our walkers initial states
    for i in range(num_walkers):
        H0squiggle_walk_states[i, 0] = # -- YOUR CODE HERE --
        alpha_walk_states[i, 0] = # -- YOUR CODE HERE --

    return H0squiggle_walk_states, alpha_walk_states


#### Step 7 - Put it all together

This is the main algorithm for MCMC

We'll start by picking a number of walkers (chains), and how many steps to take (how long the chains are)

Then, we'll initialize our walkers as you defined above.

Then, we'll step through our monte carlo simulation. At each step, we'll take each state that a walker is in, and calculate its least squares.

Then, we'll generate a new step, and calculate its least squares as well.

If our new state is a better model (has lower least squares) than our current state, we'll move there.

If our new state is NOT a better model, we'll only move there with some probability. 

You can define this probability however you like. You can use a fixed value (50/50, 60/40, etc.) or you can scale the probability with how much worse the new model is than the current model (the worse it is, the less likely you are to move there)

In [140]:
# You can change these as you see fit
num_walkers = 3
num_steps = 10000

# Initialize our walkers
my_H0_walkers, my_alpha_walkers = initialize_walkers(num_walkers, num_steps)

# Go through each step
for i in range(num_steps-1):
    # Repeat for each of our walkers
    for j in range(num_walkers):
        # Get our current values
        current_H0squiggle = my_H0_walkers[j][i]
        current_alpha = my_alpha_walkers[j][i]
        current_least_squares = get_least_squares(current_H0squiggle, current_alpha, my_z, my_H0, my_H0_err)

        # Get our next values
        next_H0squiggle, next_alpha = get_next_step(current_H0squiggle, current_alpha)
        next_least_squares = get_least_squares(next_H0squiggle, next_alpha, my_z, my_H0, my_H0_err)

        # Decide whether to accept or reject our next step

        # -- YOUR CODE HERE --

        if " Accept condition ":
            my_H0_walkers[j][i+1] = next_H0squiggle
            my_alpha_walkers[j][i+1] = next_alpha
        else: # Reject new step, stay where we are
            my_H0_walkers[j][i+1] = current_H0squiggle
            my_alpha_walkers[j][i+1] = current_alpha

### Step 8. Evaluate

We'll plot our results and print our posterior distribution.

Note that I cut the first 200 steps of our walks.

This is called *Burn in*

The burn in phase lets us ignore any effects of how we selected our starting positions and our prior. You can change this value if you'd like.

In [ ]:
# Plot our walkers and their steps
fig = plt.figure(figsize=(8,6))
plt.plot(my_H0_walkers.transpose()[200:,:])
plt.ylabel("$ \\tilde{H_{0}} $")
plt.show()
fig = plt.figure(figsize=(8,6))
plt.plot(my_alpha_walkers.transpose()[200:,:])
plt.ylabel("$ \\alpha $")
plt.show()


# Print statistics
print("Mean H0 : " + str(np.mean(my_H0_walkers.transpose()[200:,:])))
print("std. dev H0: " + str(np.std(my_H0_walkers.transpose()[200:,:])))

print("Mean alpha : " + str(np.mean(my_alpha_walkers.transpose()[200:,:])))
print("std. dev alpha: " + str(np.std(my_alpha_walkers.transpose()[200:,:])))

## Improvements

Looking at the graphs you just made and the standard deviation on your walkers, does it seem like your walkers converged to the same value?

If yes, congrats!

If not, what do you think your MCMC didn't converge? Please type your answer in the box below and then wait for everyone to discuss

Answer:
    

## Improvements - Linear Algebra

Let's re-examine our weather example:

<div>
<img src="https://deparkes.co.uk/wp-content/uploads/2020/08/GraphView.png" width="500"/>
</div>

How about, instead of using a bunch of if statements and a random number generator, we instead used a transition matrix:

|   | Sunny  | Cloudy  | Rainy  |
|---|---|---|---|
|Sunny| .7 | .1 | .2 |
|Cloudy| .2 | .3 | .5|
|Rainy | .1 | .3 |.6|

or 

# $$\begin{bmatrix} .7 & .1 & .2 \\ .2 & .3 & .5 \\ .1 & .3 & .6 \end{bmatrix}$$

We can then represent our states as row vectors - 

#### Sunny : $\begin{pmatrix} 1 & 0 & 0 \end{pmatrix}$
#### Cloudy : $\begin{pmatrix} 0 & 1 & 0 \end{pmatrix}$
#### Rainy : $\begin{pmatrix} 0 & 0 & 1 \end{pmatrix}$

And our state transition will be represented by matrix multiplication

#### Day 2 Weather = $\begin{pmatrix} 1 & 0 & 0 \end{pmatrix}$$\begin{bmatrix} .7 & .1 & .2 \\ .2 & .3 & .5 \\ .1 & .3 & .6 \end{bmatrix}$ = $\begin{pmatrix} .7 \\ .1 \\ .2 \end{pmatrix}$

And Day 3 will be the transpose of our Day 2 column vector times our state transition matrix again:

#### Day 2 Weather = $\begin{pmatrix} .7 & .1 & .2 \end{pmatrix}$$\begin{bmatrix} .7 & .1 & .2 \\ .2 & .3 & .5 \\ .1 & .3 & .6 \end{bmatrix}$ = $\begin{pmatrix} .53 \\ .16 \\ .31 \end{pmatrix}$

You will note that these steps do not have discrete states!!

Instead, they track the posterior distribution, and with each transition, we get closer and closer to the true posterior.

If you have time, use numpy to repeat this matrix multiplication a significant number of time and compare the results to our first attempt at a markov chain up above

Linear algebra speeds up our algorithm immensely, as you hopefully noticed above.

If you have time, describe how we could do something similar with our MCMC to speed up the process. Why would speeding up the process be beneficial to its accuracy? Discuss below